### ISSUE TITLE
Proposal: Have the MariaDB container pre-populated with OpenEMR database schema

### ISSUE THREAD

**Issue by ryannix123** [RedHatOfficial/openemr-kube#26]
I would like to propose that the OpenEMR database schema is pre-populated using the CentOS MariaDB 10.3 container found here: https://github.com/sclorg/mariadb-container/blob/master/10.2/root/usr/share/container-scripts/mysql/README.md

I've found the installation is much easier when the schema is already loaded.

**Comment by dixonwhitmire** [comment]
Just to chime in on @ryannix123's proposal (and hopefully not go off the rails),  I found it easier to side step the auto-configuration process as well. The community [MariaDB](https://hub.docker.com/_/mariadb) and [MySQL](https://hub.docker.com/_/mysql) images I have used, support executing "custom" SQL scripts as part of the database initialization process. I leveraged that feature by exporting the db schema post setup, so that I could utilize a streamlined process moving forward.

If anyone is interested in taking a look you can use this [image](https://hub.docker.com/layers/dixonwhitmire/openemr/5.0.2-configured/images/sha256-99c7b17df0a176f90facdce5b0d59af58a8f5f41cdefc138e7b83151cb139c69?context=repo) with the attached db schema.

I'm sure there is probably a slicker way to do this, but wanted to pass this along in case it's useful.  
fwiw here's a docker compose config my team is using to support OpenEMR. We're looking forward to moving to OpenShift and Code Ready Containers! 

```yml
version: "3.7"
services:
    openemr:
        restart: always
        image: dixonwhitmire/openemr:5.0.2-configured
        container_name: openemr     
        environment:
            - MYSQL_ROOT_PASS=${MARIADB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MARIADB_DATABASE}
            - OE_USER=${MARIADB_USER}
            - OE_PASS=${MARIADB_PASSWORD}
        ports:
            - "9090:80"
        depends_on: 
            - openemr_db
    openemr_db:
        image: mariadb/server:10.4
        container_name: openemr_db     
        command: ['mysqld','--character-set-server=utf8']        
        ports: 
            - "9091:3306"
        environment: 
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        volumes:
            - ./openemr_db:/docker-entrypoint-initdb.d
            - openemr_db_volume:/var/lib/mysql
volumes:
    openemr_db_volume: {}
```
[001_openemr.sql.zip](https://github.com/RedHatOfficial/openemr-kube/files/4477661/001_openemr.sql.zip)
